### ISSUE TITLE
links to malware

### ISSUE THREAD

**Issue by cbertelli** [minas1/windows_dropbox_sync#2]
Hello,
some of the links in this project are really dangerous. Please have a look at them.

**Comment by minas1** [comment]
I have fixed a link in the README page - it was referring to my old website that expired. Thanks for reporting this!

**Comment by cbertelli** [comment]
Not only the README page. Look at the head of the repository:
"Synchronize folders outside the Dropbox folder http://minas-mina.com/applications/windows-dropbox-sync/"
is pointing to another "suggestion". Not a good one.

**Comment by minas1** [comment]
Thanks, fixed.
